---
author_info:
  name: Vaughn Kottler
  email: vaughn@libre-embedded.com
  username: vkottler

# Use the same versions and systems that vmklib uses.
versions: ["3.12", "3.13"]
systems:
  - macos-latest
  - windows-latest
