---
author_info:
  name: Vaughn Kottler
  email: vaughnkottler@gmail.com
  username: vkottler

# Use the same versions and systems that vmklib uses.
versions: ["3.10", "3.11", "3.12"]
systems:
  - macos-latest
  - windows-latest
